version: "3.7"

services:
  nodejs:
    container_name: antd_pro_auth_mock
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
